FROM 	golang:alpine AS builder
ENV 	CGO_ENABLED=0 GOOS=linux
WORKDIR /app

RUN 	apk add --no-cache make gcc musl-dev linux-headers git
RUN 	git clone https://github.com/bnb-chain/bsc .
RUN 	make geth

## ---
FROM 	alpine

COPY 	--from=builder /app/build/bin/geth /bin/geth

RUN 	apk -U add findutils

WORKDIR /var/lib/bsc

EXPOSE 30311 30311/udp
