FROM 	golang:alpine AS builder
ENV 	CGO_ENABLED=0 GOOS=linux
WORKDIR /app

RUN 	apk add --no-cache make gcc musl-dev linux-headers git
RUN 	git clone https://github.com/bnb-chain/bsc .
RUN 	make geth

## ---
FROM 	alpine

COPY 	--from=builder /app/build/bin/geth /bin/geth
COPY 	genesis.json .

WORKDIR /var/lib/bsc

RUN 	geth init /genesis.json --datadir=./
RUN 	rm -f /var/lib/bsc/geth/nodekey

ENTRYPOINT [ "geth" ]
